### ISSUE TITLE
cnpm安装报错

### ISSUE THREAD

**Issue by MNGambler** [Jannchie/anichart.js#79]
× Install fail! Error: [anichart@2.1.1 › node-fetch-polyfill@2.0.6 › node-web-streams@0.2.2 › web-streams-polyfill@git://github.com/gwicke/web-streams-polyfill.git#spec_performance_improvements] Run "C:\Windows\system32\cmd.exe /d /s /c git clone https://github.com/gwicke/web-streams-polyfill.git C:\Users\wang2\node_modules\.tmp\4cd98833-b454-46c8-ab59-a1ab89c4f784" error, exit code 1
Error: [anichart@2.1.1 › node-fetch-polyfill@2.0.6 › node-web-streams@0.2.2 › web-streams-polyfill@git://github.com/gwicke/web-streams-polyfill.git#spec_performance_improvements] Run "C:\Windows\system32\cmd.exe /d /s /c git clone https://github.com/gwicke/web-streams-polyfill.git C:\Users\wang2\node_modules\.tmp\4cd98833-b454-46c8-ab59-a1ab89c4f784" error, exit code 1
    at module.exports (D:\node\node_modules\cnpm\node_modules\npminstall\lib\download\git.js:51:11)
    at module.exports.throw (<anonymous>)
    at onRejected (D:\node\node_modules\cnpm\node_modules\co\index.js:81:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by MNGambler** [comment]
> × Install fail! Error: [anichart@2.1.1 › node-fetch-polyfill@2.0.6 › node-web-streams@0.2.2 › web-streams-polyfill@git://github.com/gwicke/web-streams-polyfill.git#spec_performance_improvements] Run "C:\Windows\system32\cmd.exe /d /s /c git clone https://github.com/gwicke/web-streams-polyfill.git C:\Users\wang2\node_modules.tmp\4cd98833-b454-46c8-ab59-a1ab89c4f784" error, exit code 1
> Error: [anichart@2.1.1 › node-fetch-polyfill@2.0.6 › node-web-streams@0.2.2 › web-streams-polyfill@git://github.com/gwicke/web-streams-polyfill.git#spec_performance_improvements] Run "C:\Windows\system32\cmd.exe /d /s /c git clone https://github.com/gwicke/web-streams-polyfill.git C:\Users\wang2\node_modules.tmp\4cd98833-b454-46c8-ab59-a1ab89c4f784" error, exit code 1
> at module.exports (D:\node\node_modules\cnpm\node_modules\npminstall\lib\download\git.js:51:11)
> at module.exports.throw ()
> at onRejected (D:\node\node_modules\cnpm\node_modules\co\index.js:81:24)
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
